version: "3.9"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  infura-test:
    environment:
      - REDIS_DB_ADDRESS=redis:6379
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis